#!/usr/bin/env python3
"""Extract the CRYPTO frame payload from RFC 9001 appendix A.2.

The frame codec's test needs one frame whose bytes came from a document rather
than from the encoder it is testing. RFC 9001 appendix A.2 prints the unprotected
payload of the client's Initial packet: a CRYPTO frame carrying the TLS
ClientHello, followed by PADDING frames that bring the payload to 1162 bytes. The
CRYPTO frame's own bytes are `06 00 40 f1` -- type 6, offset 0, and a two-byte
length of 241 -- so the frame is transcribed from the RFC and not from this
implementation.

The payload is extracted by the rule rather than by copying a block: the hex
block after "unprotected payload of this" is read, whitespace ignored, and the
result is required to parse as a CRYPTO frame whose length matches the bytes that
follow it. A wrong extraction stops the script instead of writing a vector that
would make a wrong implementation pass.

    python3 tests/vectors/extract_rfc9001_client_initial.py [rfc9001.txt] [--check]

With no arguments it looks for `/tmp/rfc9001.txt` and writes
`tests/vectors/rfc9001_client_initial.h`. With `--check` it re-extracts and
compares against the committed header, which is what verifies that the committed
bytes are still the RFC's.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HEADER = HERE / "rfc9001_client_initial.h"


def extract(rfc_text: str) -> bytes:
    """The client Initial's payload: CRYPTO frame plus PADDING."""
    # The paragraph introduces the block; the block is the run of hex lines that
    # follows it. The first such line is found rather than assumed to be the
    # next line, because the RFC's prose and its figures are interleaved and the
    # number of prose lines between them is not a property worth depending on.
    marker = "unprotected payload of this"
    at = rfc_text.index(marker)
    lines = rfc_text[at:].splitlines()
    tokens = []
    started = False
    for line in lines:
        stripped = line.strip()
        if re.fullmatch(r"(?:[0-9a-f]{2,}(?: [0-9a-f]{2,})*)", stripped):
            started = True
            tokens.extend(stripped.split())
            continue
        if started:
            break
    if not tokens:
        raise SystemExit("no payload block found")
    payload = bytes.fromhex("".join(tokens))

    # The RFC prints the CRYPTO frame and describes the padding rather than
    # printing 917 zero bytes, so the payload is the frame followed by the
    # PADDING frames the sentence names. The count is derived from the total the
    # RFC gives, not assumed.
    frame_length = 4 + 241
    if len(payload) != frame_length:
        raise SystemExit(f"expected the printed block to be {frame_length} bytes, got {len(payload)}")
    padding = 1162 - frame_length
    payload = payload + bytes(padding)

    # Self-check: the block must be a CRYPTO frame whose declared length fits,
    # followed by nothing but PADDING frames, and the payload must be 1162 bytes
    # as the RFC says.
    if payload[0] != 0x06:
        raise SystemExit(f"expected a CRYPTO frame, got type {payload[0]:#04x}")
    if payload[1] != 0x00:
        raise SystemExit(f"expected offset 0, got {payload[1]:#04x}")
    if payload[2] != 0x40:
        raise SystemExit(f"expected a two-byte length, got {payload[2]:#04x}")
    length = ((payload[2] & 0x3F) << 8) | payload[3]
    if length != 241:
        raise SystemExit(f"expected a 241-byte ClientHello, got {length}")
    body = payload[4 : 4 + length]
    if body[0] != 0x01 or body[1] != 0x00 or body[2] != 0x00:
        raise SystemExit("the payload does not begin with a TLS handshake header")
    if set(payload[4 + length :]) != {0x00}:
        raise SystemExit("the frames after the CRYPTO frame are not all PADDING")
    if len(payload) != 1162:
        raise SystemExit(f"expected a 1162-byte payload, got {len(payload)}")
    return payload


def render(payload: bytes) -> str:
    lines = []
    line = "    "
    for index, byte in enumerate(payload):
        line += f"0x{byte:02x}, "
        if index % 12 == 11:
            lines.append(line.rstrip())
            line = "    "
    if line.strip():
        lines.append(line.rstrip())
    body = "\n".join(lines)
    return f"""/* Generated by tests/vectors/extract_rfc9001_client_initial.py -- do not edit.
 *
 * The unprotected payload of RFC 9001 appendix A.2's client Initial packet: a
 * CRYPTO frame carrying the TLS ClientHello, then PADDING frames to 1162 bytes.
 * It is the one frame vector in this project's tests that came from a document
 * rather than from the encoder under test.
 *
 * THE BYTES ARE THE RFC'S, EXTRACTED, NOT TRANSCRIBED. The script re-derives
 * them from the RFC text and refuses to write a block that does not parse as a
 * CRYPTO frame of the declared length followed by PADDING, so a bad extraction
 * stops generation rather than producing a vector a wrong implementation would
 * pass. `--check` re-extracts and compares against this file.
 */

#ifndef WT_RFC9001_CLIENT_INITIAL_H
#define WT_RFC9001_CLIENT_INITIAL_H

#include <stdint.h>

/* 1162 bytes: 4 of CRYPTO header, 241 of ClientHello, 917 of PADDING. */
#define WT_RFC9001_CLIENT_INITIAL_PAYLOAD_LEN 1162
#define WT_RFC9001_CLIENT_INITIAL_CRYPTO_OFFSET 0
#define WT_RFC9001_CLIENT_INITIAL_CRYPTO_LENGTH 241
#define WT_RFC9001_CLIENT_INITIAL_PADDING_COUNT 917
/* The first four bytes are the CRYPTO frame's header, or would be: they are
 * part of the payload and the parser reads them as the frame. */
static const uint8_t WT_RFC9001_CLIENT_INITIAL_PAYLOAD
    [WT_RFC9001_CLIENT_INITIAL_PAYLOAD_LEN] = {{
{body}
}};

#endif /* WT_RFC9001_CLIENT_INITIAL_H */
"""


def main(argv) -> int:
    check = "--check" in argv
    args = [a for a in argv[1:] if not a.startswith("--")]
    source = Path(args[0]) if args else Path("/tmp/rfc9001.txt")
    if not source.exists():
        print(f"rfc9001 text not found at {source}", file=sys.stderr)
        return 2
    payload = extract(source.read_text(encoding="utf-8"))
    rendered = render(payload)
    if check:
        if not HEADER.exists():
            print("no committed header to check", file=sys.stderr)
            return 1
        if HEADER.read_text(encoding="utf-8") != rendered:
            print("the committed header is not the RFC's payload", file=sys.stderr)
            return 1
        print("rfc9001 client Initial: committed bytes match the RFC")
        return 0
    HEADER.write_text(rendered, encoding="utf-8")
    print(f"rfc9001 client Initial: wrote {len(payload)} bytes of payload")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
