/* Generated by tests/vectors/extract_rfc7541_huffman.py -- do not edit.
 *
 * RFC 7541 appendix C.4.1's worked example: the Huffman-coded `:authority` value
 * from its first encoded header block, and the plaintext the RFC decodes it to.
 * It is the one Huffman vector in this project that did not come from this
 * implementation, which is why the decoder is checked against it.
 */

#ifndef WT_RFC7541_HUFFMAN_VECTORS_H
#define WT_RFC7541_HUFFMAN_VECTORS_H

#include <stdint.h>

#define WT_RFC7541_HUFFMAN_EXAMPLE_LENGTH 12U
static const uint8_t WT_RFC7541_HUFFMAN_EXAMPLE[WT_RFC7541_HUFFMAN_EXAMPLE_LENGTH] = {
    0xf1U, 0xe3U, 0xc2U, 0xe5U, 0xf2U, 0x3aU, 0x6bU, 0xa0U,
    0xabU, 0x90U, 0xf4U, 0xffU,
};

#define WT_RFC7541_HUFFMAN_EXAMPLE_PLAINTEXT_LENGTH 15U
static const uint8_t WT_RFC7541_HUFFMAN_EXAMPLE_PLAINTEXT
    [WT_RFC7541_HUFFMAN_EXAMPLE_PLAINTEXT_LENGTH] = {
    0x77U, 0x77U, 0x77U, 0x2eU, 0x65U, 0x78U, 0x61U, 0x6dU,
    0x70U, 0x6cU, 0x65U, 0x2eU, 0x63U, 0x6fU, 0x6dU,
};

#endif /* WT_RFC7541_HUFFMAN_VECTORS_H */
