/* Generated by tests/vectors/extract_rfc9001_retry.py -- do not edit.
 *
 * RFC 9001 appendix A.4's Retry packet and the integrity tag it prints with it.
 * The tag is what a client uses to tell a Retry the server sent from one an
 * attacker injected (section 5.8), so the value this implementation produces for
 * the document's own packet is asserted against the document's own tag rather
 * than against a round trip through the same code.
 *
 * THE BYTES ARE THE RFC'S, EXTRACTED, NOT TRANSCRIBED. The script refuses to
 * write a block that does not parse as a version-1 Retry whose original
 * destination connection ID agrees with A.2's client Initial packet, so a bad
 * extraction stops generation rather than producing a vector a wrong
 * implementation would pass. `--check` re-extracts and compares against this
 * file.
 */

#ifndef WT_RFC9001_RETRY_H
#define WT_RFC9001_RETRY_H

#include <stdint.h>

/* The client-chosen connection ID the tag is bound to. It is authenticated but
 * is not part of the Retry packet on the wire (section 5.8). */
#define WT_RFC9001_RETRY_ODCID_LEN 8
static const uint8_t WT_RFC9001_RETRY_ODCID[WT_RFC9001_RETRY_ODCID_LEN] = {
    0x83U, 0x94U, 0xc8U, 0xf0U, 0x3eU, 0x51U, 0x57U, 0x08U,
};

/* The whole Retry packet as A.4 prints it: header, token, then the tag. */
#define WT_RFC9001_RETRY_PACKET_LEN 36
static const uint8_t WT_RFC9001_RETRY_PACKET[WT_RFC9001_RETRY_PACKET_LEN] = {
    0xffU, 0x00U, 0x00U, 0x00U, 0x01U, 0x00U, 0x08U, 0xf0U,
    0x67U, 0xa5U, 0x50U, 0x2aU, 0x42U, 0x62U, 0xb5U, 0x74U,
    0x6fU, 0x6bU, 0x65U, 0x6eU, 0x04U, 0xa2U, 0x65U, 0xbaU,
    0x2eU, 0xffU, 0x4dU, 0x82U, 0x90U, 0x58U, 0xfbU, 0x3fU,
    0x0fU, 0x24U, 0x96U, 0xbaU,
};

/* The last sixteen bytes of that packet, which the implementation must
 * reproduce from the packet without them. */
#define WT_RFC9001_RETRY_TAG_LEN 16
static const uint8_t WT_RFC9001_RETRY_TAG[WT_RFC9001_RETRY_TAG_LEN] = {
    0x04U, 0xa2U, 0x65U, 0xbaU, 0x2eU, 0xffU, 0x4dU, 0x82U,
    0x90U, 0x58U, 0xfbU, 0x3fU, 0x0fU, 0x24U, 0x96U, 0xbaU,
};

#endif /* WT_RFC9001_RETRY_H */
