/* Peer authentication: certificate validation and the CertificateVerify check.
 *
 * THE TEST THAT MATTERS MOST USES ONE DOCUMENT END TO END. RFC 8448 prints a server
 * certificate, the CertificateVerify message that goes with it, and every handshake message
 * before it. So this file rebuilds the transcript through the Certificate, builds the
 * content a CertificateVerify signs from that hash, extracts the public key from the
 * certificate's own DER, and verifies the RFC's signature with it. The transcript hashing,
 * the content construction, the key extraction and the signature arithmetic all have to be
 * right for that to pass, and the expected answer is a document rather than this code.
 *
 * The chain validation cases use certificates generated by
 * tests/vectors/trust/make-fixtures.sh: a CA, a leaf it signed for example.com, a leaf for
 * another name, and a leaf signed by a CA the bundle does not contain. The one certificate
 * whose expiry is tested is not a fixture at all -- it is RFC 8448's own, which expired on
 * 30 July 2026 -- so the expiry case is a fact about a document rather than about this
 * machine's clock.
 *
 * The development bypass is checked for the restriction that comes with it: it accepts a
 * loopback name and refuses anything else, which is the property the Swift client's
 * equivalent policy has. A bypass that accepted any name would be a policy nobody should be
 * able to configure by accident.
 */

#include "wt_test.h"

#include <stdio.h>
#include <stdlib.h>

#include "webtransport/tls/handshake.h"
#include "webtransport/tls/keyschedule.h"
#include "webtransport/tls/trust.h"

#include "rfc8448_vectors.h"

#ifndef WT_TRUST_FIXTURE_DIR
#error "WT_TRUST_FIXTURE_DIR must name the directory holding the trust fixtures"
#endif

/* Read a fixture into memory. The files are small and the test is the only reader. */
static size_t read_fixture(const char *name, uint8_t *out, size_t capacity) {
  char path[512];
  FILE *file;
  size_t used;

  if (snprintf(path, sizeof(path), "%s/%s", WT_TRUST_FIXTURE_DIR, name) < 0) {
    return 0U;
  }
  file = fopen(path, "rb");
  if (file == NULL) return 0U;
  used = fread(out, 1U, capacity, file);
  fclose(file);
  return used;
}

/* Build a Certificate message around one DER certificate and parse it back, so the trust
 * layer is handed what a peer's message would have produced. */
static int certificate_from_der(const uint8_t *der, size_t der_len, uint8_t *message,
                                size_t message_capacity, size_t *message_len,
                                wt_tls_certificate_t *out) {
  wt_tls_certificate_entry_t entry;
  wt_tls_certificate_params_t params;

  entry.der = der;
  entry.der_len = der_len;
  entry.extensions = NULL;
  entry.extensions_len = 0U;
  memset(&params, 0, sizeof(params));
  params.entries = &entry;
  params.count = 1U;
  if (wt_tls_certificate_build(&params, message, message_capacity, message_len) != WT_OK) {
    return 0;
  }
  return wt_tls_certificate_parse(message, *message_len, out) == WT_OK;
}

/* The RFC 8448 certificate, as a parsed Certificate message. */
static int rfc8448_certificate(uint8_t *message, size_t message_capacity, size_t *message_len,
                               wt_tls_certificate_t *out) {
  /* The DER is the one entry inside the message the RFC prints: four bytes of header, one
   * of request context length, three of list length, and the entry's own three-byte length
   * before the certificate. */
  const uint8_t *der = WT_RFC8448_CERTIFICATE + 11U;
  const size_t der_len = 432U;
  return certificate_from_der(der, der_len, message, message_capacity, message_len, out);
}

static void test_content_construction(void) {
  uint8_t hash[WT_TLS13_SECRET_LEN];
  uint8_t server[WT_TLS_CERTIFICATE_VERIFY_CONTENT_LEN];
  uint8_t client[WT_TLS_CERTIFICATE_VERIFY_CONTENT_LEN];
  size_t i;
  int all_spaces = 1;

  memset(hash, 0x5a, sizeof(hash));
  WT_EXPECT_OK("the server content builds", wt_tls_certificate_verify_content(1, hash, server));
  WT_EXPECT_OK("the client content builds", wt_tls_certificate_verify_content(0, hash, client));

  /* Sixty-four spaces, then the context string, then a zero byte, then the hash. */
  for (i = 0U; i < 64U; i++) {
    if (server[i] != 0x20U) all_spaces = 0;
  }
  WT_EXPECT_TRUE("sixty-four spaces come first", all_spaces);
  WT_EXPECT_BYTES("then the server context string",
                  (const uint8_t *)"TLS 1.3, server CertificateVerify", server + 64U, 33U);
  WT_EXPECT_U64("then a zero byte", 0U, (uint64_t)server[64U + 33U]);
  WT_EXPECT_BYTES("then the transcript hash", hash, server + 64U + 34U, WT_TLS13_SECRET_LEN);
  WT_EXPECT_BYTES("and the client string differs",
                  (const uint8_t *)"TLS 1.3, client CertificateVerify", client + 64U, 33U);
  WT_EXPECT_INT("so the two contents differ", 0,
                memcmp(server, client, sizeof(server)) == 0 ? 1 : 0);

  WT_EXPECT_STATUS("a NULL hash is refused", WT_ERR_INVALID_ARGUMENT,
                   wt_tls_certificate_verify_content(1, NULL, server));
  WT_EXPECT_STATUS("a NULL output is refused", WT_ERR_INVALID_ARGUMENT,
                   wt_tls_certificate_verify_content(1, hash, NULL));
}

static void test_rfc8448_certificate_verify(void) {
  uint8_t message[512];
  uint8_t spki[WT_TLS_SPKI_MAX];
  uint8_t hash[WT_TLS13_SECRET_LEN];
  uint8_t content[WT_TLS_CERTIFICATE_VERIFY_CONTENT_LEN];
  wt_tls_certificate_t certificate;
  wt_tls_certificate_verify_t verify;
  wt_tls_trust_policy_t policy;
  wt_tls13_transcript_t transcript;
  size_t message_len = 0U;
  size_t spki_len = 0U;

  WT_EXPECT_TRUE("the RFC's certificate is available",
                 rfc8448_certificate(message, sizeof(message), &message_len, &certificate));

  /* The certificate is accepted by the development policy on a loopback name, which is the
   * policy that needs no trust anchor: what is under test here is the key extraction and
   * the signature, not the chain. */
  memset(&policy, 0, sizeof(policy));
  policy.mode = WT_TLS_TRUST_LOCAL_DEVELOPMENT;
  policy.host_name = "localhost";
  WT_EXPECT_OK("the development policy accepts it",
               wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  WT_EXPECT_TRUE("and extracts a public key", spki_len > 0U);
  WT_EXPECT_U64("which starts as a DER SEQUENCE", 0x30U, (uint64_t)spki[0]);

  /* The transcript through the Certificate, which is what the signature is over. Every
   * earlier checkpoint of this transcript is checked in test_tls13_keyschedule; here the
   * hash is taken one message further on. */
  WT_EXPECT_OK("the transcript starts", wt_tls13_transcript_init(&transcript));
  WT_EXPECT_OK("and takes the ClientHello",
               wt_tls13_transcript_append(&transcript, WT_RFC8448_CLIENT_HELLO,
                                          WT_RFC8448_CLIENT_HELLO_LEN));
  WT_EXPECT_OK("the ServerHello", wt_tls13_transcript_append(&transcript, WT_RFC8448_SERVER_HELLO,
                                                             WT_RFC8448_SERVER_HELLO_LEN));
  WT_EXPECT_OK("the EncryptedExtensions",
               wt_tls13_transcript_append(&transcript, WT_RFC8448_ENCRYPTED_EXTENSIONS,
                                          WT_RFC8448_ENCRYPTED_EXTENSIONS_LEN));
  WT_EXPECT_OK(
      "and the Certificate",
      wt_tls13_transcript_append(&transcript, WT_RFC8448_CERTIFICATE, WT_RFC8448_CERTIFICATE_LEN));
  WT_EXPECT_OK("the hash through the Certificate", wt_tls13_transcript_hash(&transcript, hash));
  wt_tls13_transcript_clear(&transcript);

  WT_EXPECT_OK("the content the server signed",
               wt_tls_certificate_verify_content(1, hash, content));

  WT_EXPECT_OK("the RFC's CertificateVerify parses",
               wt_tls_certificate_verify_parse(WT_RFC8448_CERTIFICATE_VERIFY,
                                               WT_RFC8448_CERTIFICATE_VERIFY_LEN, &verify));
  WT_EXPECT_U64("with its scheme", (uint64_t)WT_TLS_SIGNATURE_RSA_PSS_RSAE_SHA256,
                (uint64_t)verify.scheme);
  WT_EXPECT_OK("and the signature verifies",
               wt_tls_signature_verify(spki, spki_len, verify.scheme, content, sizeof(content),
                                       verify.signature, verify.signature_len));

  /* One bit of the signature changed, and one bit of the content changed, are both
   * refusals: the check is over both. */
  {
    uint8_t damaged[WT_RFC8448_CERTIFICATE_VERIFY_LEN];
    uint8_t other_content[WT_TLS_CERTIFICATE_VERIFY_CONTENT_LEN];
    size_t i;
    int all_rejected = 1;

    for (i = 0U; i < 8U; i++) {
      memcpy(damaged, verify.signature, verify.signature_len);
      damaged[i * 16U] ^= 0x01U;
      if (wt_tls_signature_verify(spki, spki_len, verify.scheme, content, sizeof(content), damaged,
                                  verify.signature_len) != WT_ERR_AUTHENTICATION) {
        all_rejected = 0;
      }
    }
    WT_EXPECT_TRUE("a changed signature is refused at every position tried", all_rejected);

    memcpy(other_content, content, sizeof(other_content));
    other_content[WT_TLS_CERTIFICATE_VERIFY_CONTENT_LEN - 1U] ^= 0x01U;
    WT_EXPECT_STATUS("a changed transcript hash is refused", WT_ERR_AUTHENTICATION,
                     wt_tls_signature_verify(spki, spki_len, verify.scheme, other_content,
                                             sizeof(other_content), verify.signature,
                                             verify.signature_len));
    other_content[64U] = 'X'; /* the context string, not the hash */
    WT_EXPECT_STATUS("a changed context string is refused", WT_ERR_AUTHENTICATION,
                     wt_tls_signature_verify(spki, spki_len, verify.scheme, other_content,
                                             sizeof(other_content), verify.signature,
                                             verify.signature_len));
  }

  /* The scheme decides the hash, so a scheme that does not match the signature is a
   * refusal rather than a verification against a different digest. */
  WT_EXPECT_STATUS("another RSA-PSS digest does not verify it", WT_ERR_AUTHENTICATION,
                   wt_tls_signature_verify(spki, spki_len, WT_TLS_SIGNATURE_RSA_PSS_RSAE_SHA512,
                                           content, sizeof(content), verify.signature,
                                           verify.signature_len));
  /* Namely WT_ERR_PROTOCOL rather than WT_ERR_AUTHENTICATION, and that is the stronger answer: the RSA key this
   * fixture carries cannot produce an ECDSA signature at all, so the mismatch is caught BEFORE any verification
   * (RFC 8446 section 4.2.3 binds a scheme to a key type). The assertion here used to be AUTHENTICATION, which is
   * what the code returned while it was verifying the signature with PKCS#1 v1.5 -- an algorithm section 4.2.3
   * forbids for CertificateVerify -- and calling that a failed verification is how the defect hid. */
  WT_EXPECT_STATUS("and neither does an ECDSA scheme", WT_ERR_PROTOCOL,
                   wt_tls_signature_verify(spki, spki_len, WT_TLS_SIGNATURE_ECDSA_SECP256R1_SHA256,
                                           content, sizeof(content), verify.signature,
                                           verify.signature_len));

  /* A truncated signature, an unknown scheme, and a key that is not a key. */
  WT_EXPECT_STATUS("a truncated signature is refused", WT_ERR_AUTHENTICATION,
                   wt_tls_signature_verify(spki, spki_len, verify.scheme, content, sizeof(content),
                                           verify.signature, verify.signature_len - 1U));
  WT_EXPECT_STATUS("an unknown scheme is refused", WT_ERR_UNSUPPORTED,
                   wt_tls_signature_verify(spki, spki_len, 0x9999U, content, sizeof(content),
                                           verify.signature, verify.signature_len));
  WT_EXPECT_STATUS("a key that is not a key is refused", WT_ERR_PROTOCOL,
                   wt_tls_signature_verify(spki, 1U, verify.scheme, content, sizeof(content),
                                           verify.signature, verify.signature_len));
  WT_EXPECT_STATUS("a NULL signature is refused", WT_ERR_INVALID_ARGUMENT,
                   wt_tls_signature_verify(spki, spki_len, verify.scheme, content, sizeof(content),
                                           NULL, verify.signature_len));

  WT_EXPECT_INT("rsa_pss_rsae_sha256 is supported", 1,
                wt_tls_signature_scheme_supported(WT_TLS_SIGNATURE_RSA_PSS_RSAE_SHA256));
  WT_EXPECT_INT("ed25519 is supported", 1,
                wt_tls_signature_scheme_supported(WT_TLS_SIGNATURE_ED25519));
  WT_EXPECT_INT("rsa_pkcs1_sha256 is not one this offers", 0,
                wt_tls_signature_scheme_supported(0x0401U));
}

static void test_pinned_certificate(void) {
  uint8_t message[512];
  uint8_t spki[WT_TLS_SPKI_MAX];
  uint8_t fingerprint[WT_SHA256_LEN];
  uint8_t other[4096];
  size_t message_len = 0U;
  size_t spki_len = 0U;
  size_t other_len;
  wt_tls_certificate_t certificate;
  wt_tls_certificate_t other_certificate;
  uint8_t other_message[4096];
  size_t other_message_len = 0U;
  wt_tls_trust_policy_t policy;

  WT_EXPECT_TRUE("the RFC's certificate is available",
                 rfc8448_certificate(message, sizeof(message), &message_len, &certificate));
  other_len = read_fixture("leaf.der", other, sizeof(other));
  WT_EXPECT_TRUE("the fixture leaf is available", other_len > 0U);
  WT_EXPECT_TRUE("and parses",
                 certificate_from_der(other, other_len, other_message, sizeof(other_message),
                                      &other_message_len, &other_certificate));

  /* The pin is the SHA-256 of the leaf's DER, which is what the Swift policy pins. */
  WT_EXPECT_OK("the fingerprint computes",
               wt_sha256(WT_RFC8448_CERTIFICATE + 11U, 432U, fingerprint));

  memset(&policy, 0, sizeof(policy));
  policy.mode = WT_TLS_TRUST_PINNED_CERTIFICATE;
  policy.fingerprint_count = 1U;
  memcpy(policy.fingerprints[0], fingerprint, WT_SHA256_LEN);
  WT_EXPECT_OK("a pinned certificate is accepted",
               wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  WT_EXPECT_TRUE("with its key", spki_len > 0U);

  /* A different certificate with the same pin is refused: the pin is a property of the
   * leaf, not of the mode. */
  WT_EXPECT_STATUS("another certificate is not the pinned one", WT_ERR_TRUST,
                   wt_tls_trust_verify(&policy, &other_certificate, spki, &spki_len));

  /* One bit of the fingerprint changed is a different fingerprint. */
  {
    wt_tls_trust_policy_t wrong = policy;
    wrong.fingerprints[0][WT_SHA256_LEN - 1U] ^= 0x01U;
    WT_EXPECT_STATUS("a fingerprint that differs by one bit is refused", WT_ERR_TRUST,
                     wt_tls_trust_verify(&wrong, &certificate, spki, &spki_len));
  }

  /* A policy with no fingerprints cannot accept anything, and says so as a caller error
   * rather than as an untrusted peer. */
  {
    wt_tls_trust_policy_t empty = policy;
    empty.fingerprint_count = 0U;
    WT_EXPECT_STATUS("a policy with no fingerprints is a caller error", WT_ERR_INVALID_ARGUMENT,
                     wt_tls_trust_verify(&empty, &certificate, spki, &spki_len));
  }

  /* A chain with no leaf is refused rather than read past. */
  {
    wt_tls_certificate_t none;
    memset(&none, 0, sizeof(none));
    WT_EXPECT_STATUS("an empty chain is refused", WT_ERR_TRUST,
                     wt_tls_trust_verify(&policy, &none, spki, &spki_len));
  }
}

static void test_development_policy(void) {
  uint8_t message[512];
  uint8_t spki[WT_TLS_SPKI_MAX];
  size_t message_len = 0U;
  size_t spki_len = 0U;
  wt_tls_certificate_t certificate;
  wt_tls_trust_policy_t policy;

  WT_EXPECT_TRUE("the RFC's certificate is available",
                 rfc8448_certificate(message, sizeof(message), &message_len, &certificate));

  memset(&policy, 0, sizeof(policy));
  policy.mode = WT_TLS_TRUST_LOCAL_DEVELOPMENT;
  policy.host_name = "localhost";
  WT_EXPECT_OK("localhost is accepted",
               wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  policy.host_name = "127.0.0.1";
  WT_EXPECT_OK("and so is 127.0.0.1", wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  policy.host_name = "::1";
  WT_EXPECT_OK("and ::1", wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));

  /* THE RESTRICTION IS THE POINT OF THE MODE. A development bypass that accepted any name
   * would be one nobody should be able to configure by accident. */
  policy.host_name = "example.com";
  WT_EXPECT_STATUS("a real name is refused", WT_ERR_TRUST,
                   wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  policy.host_name = "localhost.example.com";
  WT_EXPECT_STATUS("and so is a name that merely contains one", WT_ERR_TRUST,
                   wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  policy.host_name = NULL;
  WT_EXPECT_STATUS("and so is no name at all", WT_ERR_TRUST,
                   wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
}

static void test_chain_validation(void) {
  uint8_t bundle[8192];
  uint8_t leaf[4096];
  uint8_t other_host[4096];
  uint8_t unknown_ca[4096];
  uint8_t message[8192];
  uint8_t spki[WT_TLS_SPKI_MAX];
  size_t bundle_len;
  size_t leaf_len;
  size_t other_host_len;
  size_t unknown_ca_len;
  size_t message_len = 0U;
  size_t spki_len = 0U;
  wt_tls_certificate_t certificate;
  wt_tls_trust_policy_t policy;

  bundle_len = read_fixture("ca.pem", bundle, sizeof(bundle));
  leaf_len = read_fixture("leaf.der", leaf, sizeof(leaf));
  other_host_len = read_fixture("leaf-other-host.der", other_host, sizeof(other_host));
  unknown_ca_len = read_fixture("leaf-unknown-ca.der", unknown_ca, sizeof(unknown_ca));
  WT_EXPECT_TRUE("the CA bundle is available", bundle_len > 0U);
  WT_EXPECT_TRUE("the leaf is available", leaf_len > 0U);
  WT_EXPECT_TRUE("the other-host leaf is available", other_host_len > 0U);
  WT_EXPECT_TRUE("the unknown-CA leaf is available", unknown_ca_len > 0U);

  memset(&policy, 0, sizeof(policy));
  policy.mode = WT_TLS_TRUST_STORE;
  policy.ca_bundle = bundle;
  policy.ca_bundle_len = bundle_len;
  policy.host_name = "example.com";

  /* A chain that validates: the leaf's issuer is in the bundle and the name matches. */
  WT_EXPECT_TRUE("the leaf parses", certificate_from_der(leaf, leaf_len, message, sizeof(message),
                                                         &message_len, &certificate));
  WT_EXPECT_OK("a valid chain is accepted",
               wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  WT_EXPECT_TRUE("and gives a public key", spki_len > 0U);

  /* The name is part of validation, not a second step: this leaf is signed by the trusted
   * CA and names another host. */
  WT_EXPECT_TRUE("the other-host leaf parses",
                 certificate_from_der(other_host, other_host_len, message, sizeof(message),
                                      &message_len, &certificate));
  WT_EXPECT_STATUS("a leaf for another name is refused", WT_ERR_TRUST,
                   wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  policy.host_name = "other.example";
  WT_EXPECT_OK("and accepted for the name it does have",
               wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));
  policy.host_name = "example.com";

  /* An issuer the bundle does not contain. */
  WT_EXPECT_TRUE("the unknown-CA leaf parses",
                 certificate_from_der(unknown_ca, unknown_ca_len, message, sizeof(message),
                                      &message_len, &certificate));
  WT_EXPECT_STATUS("a chain with an unknown issuer is refused", WT_ERR_TRUST,
                   wt_tls_trust_verify(&policy, &certificate, spki, &spki_len));

  /* RFC 8448's certificate is self-signed and expired, so a store that trusts it as its
   * own anchor still refuses it. This is the expiry case, and the expiry is a fact in a
   * document rather than in this machine's clock. */
  {
    uint8_t rfc_message[512];
    wt_tls_certificate_t rfc_certificate;
    size_t rfc_len = 0U;
    WT_EXPECT_TRUE(
        "the RFC's certificate is available",
        rfc8448_certificate(rfc_message, sizeof(rfc_message), &rfc_len, &rfc_certificate));
    policy.ca_bundle = WT_RFC8448_CERTIFICATE + 11U;
    policy.ca_bundle_len = 432U; /* DER, which is not PEM: the bundle is refused */
    WT_EXPECT_STATUS("a bundle that is not PEM is refused", WT_ERR_TRUST,
                     wt_tls_trust_verify(&policy, &rfc_certificate, spki, &spki_len));
    policy.ca_bundle = bundle;
    policy.ca_bundle_len = bundle_len;
    WT_EXPECT_STATUS("a certificate from another issuer is refused", WT_ERR_TRUST,
                     wt_tls_trust_verify(&policy, &rfc_certificate, spki, &spki_len));
  }

  /* A store with no bundle cannot validate anything. */
  {
    wt_tls_trust_policy_t empty = policy;
    empty.ca_bundle = NULL;
    empty.ca_bundle_len = 0U;
    WT_EXPECT_TRUE(
        "the leaf parses again",
        certificate_from_der(leaf, leaf_len, message, sizeof(message), &message_len, &certificate));
    WT_EXPECT_STATUS("an empty store refuses", WT_ERR_TRUST,
                     wt_tls_trust_verify(&empty, &certificate, spki, &spki_len));
  }

  /* The SYSTEM mode validates against the platform, which may have no store at all and
   * certainly does not trust a generated test CA. It must never accept this leaf, and it
   * says which of the two states it is in rather than failing silently. */
  {
    wt_tls_trust_policy_t system_policy;
    wt_status_t status;
    memset(&system_policy, 0, sizeof(system_policy));
    system_policy.mode = WT_TLS_TRUST_SYSTEM;
    system_policy.host_name = "example.com";
    status = wt_tls_trust_verify(&system_policy, &certificate, spki, &spki_len);
    WT_EXPECT_TRUE("the platform store does not trust a test CA",
                   status == WT_ERR_TRUST || status == WT_ERR_UNSUPPORTED);
  }

  /* A mode that is not a mode is a caller error rather than a refusal of the peer. */
  {
    wt_tls_trust_policy_t bogus = policy;
    bogus.mode = (wt_tls_trust_mode_t)99;
    WT_EXPECT_STATUS("an unknown mode is a caller error", WT_ERR_INVALID_ARGUMENT,
                     wt_tls_trust_verify(&bogus, &certificate, spki, &spki_len));
    WT_EXPECT_STATUS("a NULL policy is a caller error", WT_ERR_INVALID_ARGUMENT,
                     wt_tls_trust_verify(NULL, &certificate, spki, &spki_len));
    WT_EXPECT_STATUS("a NULL output is a caller error", WT_ERR_INVALID_ARGUMENT,
                     wt_tls_trust_verify(&policy, &certificate, NULL, &spki_len));
    WT_EXPECT_STATUS("a NULL length output is a caller error", WT_ERR_INVALID_ARGUMENT,
                     wt_tls_trust_verify(&policy, &certificate, spki, NULL));
  }
}

/* AUD-0030. Both trusting modes reach `parse_first` with the certificate's bytes, and both had
 * their "the bytes are not a certificate" refusal unexecuted: the PINNED path after the
 * fingerprint matched, and the development path after the loopback name was accepted. That is
 * the interesting case for each -- a peer that knows the pin, or that is talking to a loopback
 * endpoint, still must send a parseable certificate, and neither mode may read past the failure.
 * The fingerprint is computed over the malformed bytes here, so the pin MATCHES and the parse is
 * the only thing that can refuse. */
static void test_unparseable_certificate_is_refused(void) {
  static const uint8_t not_a_certificate[] = {0x30U, 0x03U, 0x02U, 0x01U, 0x01U};
  uint8_t spki[WT_TLS_SPKI_MAX];
  size_t spki_len = 0U;
  uint8_t digest[WT_SHA256_LEN];
  wt_tls_certificate_t malformed;
  wt_tls_trust_policy_t policy;

  memset(&malformed, 0, sizeof(malformed));
  malformed.entries[0].der = not_a_certificate;
  malformed.entries[0].der_len = sizeof(not_a_certificate);
  malformed.count = 1U;

  WT_EXPECT_OK("the unparseable bytes hash",
               wt_sha256(not_a_certificate, sizeof(not_a_certificate), digest));

  /* Pinned mode: the fingerprint matches, so the refusal can only be the parse. */
  memset(&policy, 0, sizeof(policy));
  policy.mode = WT_TLS_TRUST_PINNED_CERTIFICATE;
  policy.fingerprint_count = 1U;
  memcpy(policy.fingerprints[0], digest, WT_SHA256_LEN);
  WT_EXPECT_STATUS("a matching pin over unparseable bytes is still refused", WT_ERR_PROTOCOL,
                   wt_tls_trust_verify(&policy, &malformed, spki, &spki_len));

  /* Local development: the name is loopback, so the bypass applies and only the parse refuses. */
  memset(&policy, 0, sizeof(policy));
  policy.mode = WT_TLS_TRUST_LOCAL_DEVELOPMENT;
  policy.host_name = "localhost";
  WT_EXPECT_STATUS("the development bypass does not excuse unparseable bytes", WT_ERR_PROTOCOL,
                   wt_tls_trust_verify(&policy, &malformed, spki, &spki_len));
}

int main(void) {
  WT_EXPECT_OK("the crypto backend initialises", wt_crypto_init());

  test_content_construction();
  test_rfc8448_certificate_verify();
  test_pinned_certificate();
  test_development_policy();
  test_chain_validation();
  test_unparseable_certificate_is_refused();

  WT_TEST_MAIN_END("wt_tls13_trust");
}
